/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:db09f7ec-ea29-4f6a-9844-8ea46ab8f820",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_kAheVW9dF",
    "aws_user_pools_web_client_id": "1jgc8vflhs51fl81fdkkqmuh4s",
    "oauth": {}
};


export default awsmobile;
